"""schema initial : bien, note de visite, historique de prix, journal

Revision ID: 4415beab2776
Revises: 
Create Date: 2026-09-13 13:20:09.791928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4415beab2776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('commune', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('prix_cents', sa.Integer(), nullable=False),
    sa.Column('prix_initial_cents', sa.Integer(), nullable=False),
    sa.Column('chambres', sa.Integer(), nullable=True),
    sa.Column('surface_habitable', sa.Integer(), nullable=True),
    sa.Column('surface_terrain', sa.Integer(), nullable=True),
    sa.Column('peb_label', sa.String(length=1), nullable=True),
    sa.Column('peb_score', sa.Integer(), nullable=True),
    sa.Column('peb_cause', sa.Text(), nullable=True),
    sa.Column('garage', sa.Boolean(), nullable=False),
    sa.Column('garage_potentiel', sa.Boolean(), nullable=False),
    sa.Column('arret_proche', sa.String(length=120), nullable=True),
    sa.Column('minutes_marche', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('raison_ecart', sa.Text(), nullable=True),
    sa.Column('premiere_vue', sa.Date(), nullable=False),
    sa.Column('derniere_vue', sa.Date(), nullable=False),
    sa.Column('description_brute', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('notes_libres', sa.Text(), nullable=True),
    sa.Column('telephone_agence', sa.String(length=40), nullable=True),
    sa.Column('cree_le', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.create_index('ix_bien_statut', ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_bien_url_hash'), ['url_hash'], unique=True)

    op.create_table('journal_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('annonces_vues', sa.Integer(), nullable=False),
    sa.Column('annonces_retenues', sa.Integer(), nullable=False),
    sa.Column('erreurs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_execution_date'), ['date'], unique=False)

    op.create_table('historique_prix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=False),
    sa.Column('prix_cents', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bien_id'], ['bien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historique_prix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historique_prix_bien_id'), ['bien_id'], unique=False)

    op.create_table('note_visite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=False),
    sa.Column('critere', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bien_id'], ['bien.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bien_id', 'critere', name='uq_note_bien_critere')
    )
    with op.batch_alter_table('note_visite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_visite_bien_id'), ['bien_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_visite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_visite_bien_id'))

    op.drop_table('note_visite')
    with op.batch_alter_table('historique_prix', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historique_prix_bien_id'))

    op.drop_table('historique_prix')
    with op.batch_alter_table('journal_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_execution_date'))

    op.drop_table('journal_execution')
    with op.batch_alter_table('bien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bien_url_hash'))
        batch_op.drop_index('ix_bien_statut')

    op.drop_table('bien')
    # ### end Alembic commands ###
